# Définition du pipeline CI/CD
stages:
  - plan
  - apply

# Définition des jobs
terraform_plan:
  stage: plan
  script:
    - terraform init
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan

terraform_apply:
  stage: apply
  script:
    - terraform apply tfplan
  only:
    - master
