---
- name: Deploy Docker Containers
  hosts: fedora_coreos
  become: yes
  tasks:
    - name: Ensure Docker is installed
      package:
        name: docker
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image
      docker_image:
        name: nginx
        source: pull

    - name: Run Docker container
      docker_container:
        name: nginx_container
        image: nginx
        state: started
        ports:
          - "80:80"
