---
- name: Deploy MariaDB Container
  hosts: fedora_coreos
  become: yes
  vars:
    mariadb_root_password: 'root'
    mariadb_database: 'example_db'
    mariadb_user: 'user'
    mariadb_password: 'user'
    mariadb_container_name: 'mariadb_container'
    mariadb_image: 'mariadb:latest'
    mariadb_port: 5000
    mariadb_data_dir: /opt/mariadb_data

  tasks:
    - name: Ensure the MariaDB data directory exists
      file:
        path: "{{ mariadb_data_dir }}"
        state: directory

    - name: Set ownership on the MariaDB data directory
      file:
        path: "{{ mariadb_data_dir }}"
        owner: 1001
        group: 1001
        mode: '0755'

    - name: Pull MariaDB image from Docker Hub
      docker_image:
        name: "{{ mariadb_image }}"
        source: pull

    - name: Run MariaDB container
      docker_container:
        name: "{{ mariadb_container_name }}"
        image: "{{ mariadb_image }}"
        state: started
        restart_policy: always
        ports:
          - "{{ mariadb_port }}:3306"
        env:
          MARIADB_ROOT_PASSWORD: "{{ mariadb_root_password }}"
          MARIADB_DATABASE: "{{ mariadb_database }}"
          MARIADB_USER: "{{ mariadb_user }}"
          MARIADB_PASSWORD: "{{ mariadb_password }}"
        volumes:
          - "{{ mariadb_data_dir }}:/var/lib/mysql"

    - name: Wait for MariaDB container to be ready
      wait_for:
        port: "{{ mariadb_port }}"
        delay: 10
        timeout: 300
