---
- name: Install and run Wireshark container
  hosts: all
  become: yes
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Docker is started and enabled
      service:
        name: docker
        state: started
        enabled: true

  - name: Pull Grafana Docker image
      docker_image:
        name: grafana/grafana
        source: pull

  - name: Run Grafana container
      docker_container:
        name: grafana
        image: grafana/grafana
        state: started
        restart_policy: always
        ports:
          - "4000:4000"
        env:
          GF_SECURITY_ADMIN_PASSWORD: "admin"  # Set admin password (change as needed)
          GF_SECURITY_ADMIN_USER: "admin"  # Set admin username (change as needed)
          GF_SERVER_HTTP_PORT: "4000"  # Change Grafana port to 4000
