---
- name: Deploy Docker Containers
  hosts: fedora_coreos
  become: yes
  tasks:

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image
      docker_image:
        name: nginx
        source: pull

    - name: Run Docker container
      docker_container:
        name: nginx_container
        image: nginx
        state: started
        ports:
          - "80:80"

    - name: Ensure latest version of Docker is installed
      command: dnf install -y docker
      when: "'Docker version 20' not in docker_version.stdout"

    - name: Pull Docker image
      docker_image:
        name: nginx:latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: nginx_container
        image: nginx:latest
        state: started
        ports:
          - "80:80"

    - name: Ensure required packages are installed
      rpm-ostree:
        name: dnf-plugins-core
        state: present

    - name: Install Wireshark
      rpm-ostree:
        name: wireshark
        state: present
      register: wireshark_result

    - name: Debug Wireshark installation
      debug:
        msg: "Wireshark installation: {{ wireshark_result }}"
