---
- name: Deploy Docker Containers
  hosts: fedora_coreos
  become: yes
  tasks:
    - name: Ensure required packages are installed
      package:
        name: 
          - dnf-plugins-core
        state: present

    - name: Ensure Docker is installed
      package:
        name: docker
        state: present

    - name: Check if Docker is installed
      command: docker --version
      register: docker_version
      failed_when: docker_version.rc != 0
      changed_when: false

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Ensure latest version of Docker is installed
      command: dnf install -y docker
      when: docker_version.stdout is search("Docker version 20")

    - name: Pull Docker image
      docker_image:
        name: nginx:latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: nginx_container
        image: nginx:latest
        state: started
        ports:
          - "80:80"
