---
- name: Install and configure JUnit
  hosts: all
  become: yes

  tasks:
    - name: Ensure Java is installed
      apt:
        name: openjdk-11-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Java is installed
      yum:
        name: java-11-openjdk-devel
        state: present
      when: ansible_os_family == "RedHat"

    - name: Download JUnit jar
      get_url:
        url: https://search.maven.org/remotecontent?filepath=junit/junit/4.13.2/junit-4.13.2.jar
        dest: /opt/junit-4.13.2.jar

    - name: Download Hamcrest jar (JUnit dependency)
      get_url:
        url: https://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
        dest: /opt/hamcrest-core-1.3.jar

    - name: Create JUnit service file
      copy:
        dest: /etc/systemd/system/junit.service
        content: |
          [Unit]
          Description=JUnit Service
          After=network.target

          [Service]
          Type=simple
          ExecStart=/usr/bin/java -jar /opt/junit-4.13.2.jar
          ExecStartPost=/bin/bash -c 'echo "Running on port 6000"'

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd to apply new service
      command: systemctl daemon-reload

    - name: Enable JUnit service to start on boot
      systemd:
        name: junit
        enabled: yes

    - name: Start JUnit service
      systemd:
        name: junit
        state: started

    - name: Ensure firewall is allowing port 6000
      ufw:
        rule: allow
        port: 6000
        proto: tcp
      when: ansible_os_family == "Debian"

    - name: Ensure firewall is allowing port 6000
      firewalld:
        port: 6000/tcp
        permanent: yes
        state: enabled
      when: ansible_os_family == "RedHat"
