---
- name: Deploy Docker Containers
  hosts: fedora_coreos
  become: yes
  tasks:

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image
      docker_image:
        name: nginx
        source: pull

    - name: Run Docker container
      docker_container:
        name: nginx_container
        image: nginx
        state: started
        ports:
          - "80:80"

- name: Install Wireshark
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Wireshark
      apt:
        name: wireshark
        state: present

    - name: Ensure non-root users can capture packets
      lineinfile:
        path: /etc/group
        regexp: '^wireshark:'
        line: 'wireshark:x:{{ lookup("pipe", "getent group wireshark | cut -d: -f3") }}:{{ ansible_user_id }}'
        state: present

    - name: Add current user to the Wireshark group
      user:
        name: "{{ ansible_user_id }}"
        groups: wireshark
        append: yes

    - name: Inform user to log out and log back in
      debug:
        msg: "You need to log out and log back in for the group changes to take effect."

