---
- name: Install Wireshark
  hosts: all
  become: yes
  tasks:
    - name: Check if python3-apt is already installed
      command: dpkg -l python3-apt
      register: python3_apt_installed
      ignore_errors: yes

    - name: Install python3-apt if not installed
      apt:
        name: python3-apt
        state: present
      when: python3_apt_installed.rc != 0

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Wireshark
      apt:
        name: wireshark
        state: present

    - name: Ensure non-root users can capture packets
      lineinfile:
        path: /etc/group
        regexp: '^wireshark:'
        line: 'wireshark:x:{{ lookup("pipe", "getent group wireshark | cut -d: -f3") }}:{{ ansible_user_id }}'
        state: present

    - name: Add current user to the Wireshark group
      user:
        name: "{{ ansible_user_id }}"
        groups: wireshark
        append: yes

    - name: Inform user to log out and log back in
      debug:
        msg: "You need to log out and log back in for the group changes to take effect."
